spring.application.name=mo_ha
#
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health,info,metrics
# Always sample.
management.tracing.sampling.probability=1.0
# Only TraceID, not SpanID.
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-}]
#
notification.rest.url=http://localhost:8080/internal/notifications/stub