spring.application.name=mo_ha
#
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-components=always
# Always sample.
management.tracing.sampling.probability=1.0
# Only TraceID, not SpanID.
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-}]
#
notification.rest.url=http://localhost:8080/internal/notifications/stub
notification.rest.health-url=http://localhost:8080/internal/notifications/stub/health
notification.rest.connect-timeout=PT2S
notification.rest.read-timeout=PT5S
#
management.metrics.enable.all=false
management.metrics.enable.config_changes_recorded_total=true
management.metrics.enable.http.server=true